program Process;

uses
  ShareMem,
  OLEAuto,
  Forms,
  SysUtils,
  Angle in '..\General\Angle.pas',
  DASFile in '..\General\DASFile.pas',
  Description in '..\General\Description.pas',
  DRFile in '..\General\DRFile.pas',
  DRTranslator in '..\General\DRTranslator.pas',
  FileIterator in '..\General\FileIterator.pas',
  FloatMatrix in '..\General\FloatMatrix.pas',
  FormatSettings in '..\General\FormatSettings.pas',
  FormUtils in '..\General\FormUtils.pas',
  Measure in '..\General\Measure.pas',
  Movement in '..\General\Movement.pas',
  Notify in '..\General\Notify.pas',
  Plane in '..\General\Plane.pas',
  RadarPlane in '..\General\RadarPlane.pas',
  TimeUtils in '..\General\TimeUtils.pas',
  Translator in '..\General\Translator.pas',
  Translators in '..\General\Translators.pas',
  TreeImages in '..\General\TreeImages.pas',
  UtStr in '..\General\utStr.pas',
  VersionInfo in '..\General\VersionInfo.pas',
  VestaFile in '..\General\VestaFile.pas',
  VestaTranslator in '..\General\VestaTranslator.pas',
  AboutDialog in '..\General\AboutDialog.pas' {FAboutDialog},
  Shell_Process in 'Forms\Shell_Process.pas' {FShell},
  ObservationForm in 'Forms\ObservationForm.pas' {FObservation},
  TimeSpanForm in 'Forms\TimeSpanForm.pas' {FTimeSpan},
  GridForm in 'Forms\GridForm.pas' {FGrid},
  ConfigurationForm in 'Forms\ConfigurationForm.pas' {FConfiguration},
  GapForm in 'Forms\GapForm.pas' {FGapColor},
  EditForm in 'Forms\EditForm.pas' {FEdit},
  HorzEdit in 'Forms\HorzEdit.pas' {FHorzEdit},
  VertEdit in 'Forms\VertEdit.pas' {FVertEdit},
  PPIEdit in 'Forms\PPIEdit.pas' {FPPIEdit},
  RHIEdit in 'Forms\RHIEdit.pas' {FRHIEdit},
  CutEdit in 'Forms\CutEdit.pas' {FCutEdit},
  CAPPIEdit in 'Forms\CAPPIEdit.pas' {FCAPPIEdit},
  TopsEdit in 'Forms\TopsEdit.pas' {FTopsEdit},
  MaxsEdit in 'Forms\MaxsEdit.pas' {FMaxsEdit},
  VILEdit in 'Units\VILEdit.pas' {FVilEdit},
  TopDownEdit in 'Forms\TopDownEdit.pas' {FTopDownEdit},
  NthSthEdit in 'Forms\NthSthEdit.pas' {FNthSthEdit},
  EstWstEdit in 'Forms\EstWstEdit.pas' {FEstWstEdit},
  ContributionEdit in 'Forms\ContributionEdit.pas' {FContributionEdit},
  VolumeEdit in 'Forms\VolumeEdit.pas' {FVolumeEdit},
  AccumulateEdit in 'Forms\AccumulateEdit.pas' {FAcumulateEdit},
  ScaleEditForm in 'Forms\ScaleEditForm.pas' {FScaleEdit},
  SettingsForm in 'Forms\SettingsForm.pas' {FSettings},
  ReportEdit in 'Forms\ReportEdit.pas' {FReportEdit},
  RTFReportForm in 'Forms\RTFReportForm.pas' {FRTFReport},
  TXTReportForm in 'Forms\TXTReportForm.pas' {FTXTReport},
  EnsembleForm in 'Forms\EnsembleForm.pas' {FEnsemble},
  Raw_Parameters in 'Forms\Raw_Parameters.pas' {FRaw_Parameters},
  Antenna in '..\Components\Antenna.pas',
  Area in '..\Components\Area.pas',
  Bargauge in '..\Components\BarGauge.pas',
  Accumulate in 'Units\Accumulate.pas',
  Animation in 'Units\Animation.pas',
  AnimationAuto in 'Units\AnimationAuto.pas',
  Border in 'Units\Border.pas',
  Borders in 'Units\Borders.pas',
  WindScan in 'Units\WindScan.pas',
  ChannelAuto in 'Units\ChannelAuto.pas',
  Configuration in 'Units\Configuration.pas',
  Contribution in 'Units\Contribution.pas',
  ContributionScan in 'Units\ContributionScan.pas',
  Correction in 'Units\Correction.pas',
  Cut in 'Units\Cut.pas',
  CutGrid in 'Units\CutGrid.pas',
  DataSource in 'Units\DataSource.pas',
  EstWst in 'Units\EstWst.pas',
  EstWstGrid in 'Units\EstWstGrid.pas',
  FormAuto in 'Units\FormAuto.pas',
  Grid in 'Units\Grid.pas',
  GridProduct in 'Units\GridProduct.pas',
  HeightTable in 'Units\HeightTable.pas',
  HorzProduct in 'Units\HorzProduct.pas',
  Macro in 'Units\Macro.pas',
  Maxs in 'Units\Maxs.pas',
  MaxsScan in 'Units\MaxsScan.pas',
  NthSth in 'Units\NthSth.pas',
  NthSthGrid in 'Units\NthSthGrid.pas',
  Observation in 'Units\Observation.pas',
  ObservationAuto in 'Units\ObservationAuto.pas',
  PPI in 'Units\ppi.pas',
  PPIScan in 'Units\PPIScan.pas',
  Product in 'Units\Product.pas',
  Products in 'Units\Products.pas',
  PRTable in 'Units\PRTable.pas',
  RadarData in 'Units\RadarData.pas',
  Referenced in 'Units\Referenced.pas',
  Region in 'Units\Region.pas',
  Regions in 'Units\Regions.pas',
  Report in 'Units\Report.pas',
  Result in 'Units\Result.pas',
  RHI in 'Units\RHI.pas',
  RHIGrid in 'Units\RHIGrid.pas',
  RHIScan in 'Units\RHIScan.pas',
  Scale in 'Units\Scale.pas',
  Scales in 'Units\Scales.pas',
  Scan in 'Units\Scan.pas',
  ScanGrid in 'Units\ScanGrid.pas',
  Settings in 'Units\Settings.pas',
  ShellAuto in 'Units\ShellAuto.pas',
  TimeSpan in 'Units\TimeSpan.pas',
  TimeSpanAuto in 'Units\TimeSpanAuto.pas',
  TopDown in 'Units\TopDown.pas',
  TopDownScan in 'Units\TopDownScan.pas',
  Tops in 'Units\Tops.pas',
  TopsScan in 'Units\TopsScan.pas',
  VertProduct in 'Units\VertProduct.pas',
  VIL in 'Units\VIL.pas',
  VILScan in 'Units\VILScan.pas',
  Volume in 'Units\Volume.pas',
  GridAuto in 'Units\GridAuto.pas',
  VestaPlane in '..\General\VestaPlane.pas',
  RadarScan in 'Units\RadarScan.pas',
  Radars in '..\General\Radars.pas',
  CDFFile in '..\General\CDFFile.pas',
  PlaneAuto in '..\General\PlaneAuto.pas',
  Topography in 'Units\Topography.pas',
  EnsembleAuto in 'Units\EnsembleAuto.pas',
  Ensemble in 'Units\Ensemble.pas',
  McGill_File in '..\General\McGill_File.pas',
  McGill_Translator in '..\General\McGill_Translator.pas',
  RAWFile in '..\General\RAWFile.pas',
  Raw_Translator in '..\General\Raw_Translator.pas',
  Tools in '..\General\Tools.pas',
  GIFImage in '..\General\GIFImage.pas',
  SpatialAnimation in 'Units\SpatialAnimation.pas',
  SpatialEdit in 'Forms\SpatialEdit.pas' {FSpatialEdit},
  XSTranslator in '..\General\XSTranslator.pas',
  CalibFile in '..\Capture\Units\CalibFile.pas',
  utMath in '..\General\UtMath.pas',
  Profile in 'Units\Profile.pas',
  ProfileEdit in 'Forms\ProfileEdit.pas' {FProfileEdit},
  ProfileVector in 'Units\ProfileVector.pas',
  Profile_Display in '..\Components\Profile_Display.pas',
  ZLibEx in '..\General\ZLibEx.pas',
  NetCDF_Translator in '..\General\NetCDF_Translator.pas',
  CalResForm in 'Forms\CalResForm.pas' {FCalRes},
  CalAcmDisForm in 'Forms\CalAcmDisForm.pas' {FCalAcmDis},
  CalAltForm in 'Forms\CalAltForm.pas' {FCalAlt},
  CalConForm in 'Forms\CalConForm.pas' {FCalCon},
  CalEstForm in 'Forms\CalEstForm.pas' {FCalEst},
  CalMovForm in 'Forms\CalMovForm.pas' {FCalMov},
  CalPotForm in 'Forms\CalPotForm.pas' {FCalPot},
  CalRefForm in 'Forms\CalRefForm.pas' {FCalRef},
  CalcFunctions in '..\General\CalcFunctions.pas',
  CalPreForm in 'Forms\CalPreForm.pas' {FCalPre},
  SupressStatus in 'Units\SupressStatus.pas',
  CAPPIScan in 'Units\CAPPIScan.pas',
  CAPPI in 'Units\CAPPI.pas',
  WindGrid in 'Units\WindGrid.pas',
  RadarVector in 'Units\RadarVector.pas',
  MatLab in 'Units\MatLab.pas',
  Rainbow5_Translator in '..\General\Rainbow5_Translator.pas',
  Rainbow5_File in '..\General\Rainbow5_File.pas',
  Qt in '..\General\Qt.pas',
  AutoPilotForm in 'Forms\AutoPilotForm.pas' {FAutoPilot},
  EditAutoPilotForm in 'Forms\EditAutoPilotForm.pas' {FEditAutoPilot},
  CircleEditForm in 'Forms\CircleEditForm.pas' {FCircleEdit},
  EditNMEAForm in 'Forms\EditNMEAForm.pas' {FEditNMEA},
  Nexrad_Translator in '..\General\Nexrad_Translator.pas',
  Nexrad_File in '..\General\Nexrad_File.pas',
  bzip2 in '..\General\bzip2.pas',
  TranslatorPercentForm in 'Forms\TranslatorPercentForm.pas' {FTranslatorPercent},
  CODE_messages in '..\General\CODE_messages.pas';

{$E exe}

exports
  DLLGetClassObject,
  DLLCanUnloadNow,
  DLLRegisterServer,
  DLLUnregisterServer;

{$R *.res}
{$R Resource.res}

begin
  Application.Initialize;
  Application.Title := 'Proceso';
  Application.UpdateFormatSettings := false;
  Application.CreateForm(TFShell, FShell);
  Application.CreateForm(TFAutoPilot, FAutoPilot);
  Application.CreateForm(TFEditAutoPilot, FEditAutoPilot);
  Application.CreateForm(TFEditNMEA, FEditNMEA);
  Application.CreateForm(TFTranslatorPercent, FTranslatorPercent);
  Application.Run;
end.

